version: '3.8'

services:
  frontend:
    build:
      context: ./contact-manager-frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./contact-manager-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CONNECTION_STRING=${CONNECTION_STRING}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    ports:
      - "5000:5000"
    restart: always